export const MixpanelEvents = {
  USER_LANDED: "User Landed",
  USER_SIGNED_IN: "Andrew Sign In Success",
  USER_SELECTED_SERVICE: "Selected Service",
  USER_SELECTED_DATE: "Selected Date",
  USER_SELECTED_TIME: "Selected Time",
  USER_SELECTED_REQUEST_DETAILS: "Selected Request Details",
  USER_SELECTED_SOURCE: "Selected Source",
  USER_SELECTED_DESTINATION: "Selected Destination",
  USER_OPENED_MAP: "Opened Map",
  USER_CLICKED_ON_TNC: "Clicked TnC",
  USER_RATED_PLATFORM: "Rating",
  USER_CLICKED_SHARE: "Shared App",
  USER_VIEWED_ABOUT: "Viewed About Page",
  USER_COMPLETED_REQUEST: "Completed Request",
  USER_VIEWED_CARPOOL: "Opened Carpool",
  USER_GOT_SUCCESS_SCREEN: "Confirmation Screen",
};
